const wordList = [
  { word: "addition", hint: "The process of combining numbers to find their total.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "subtraction", hint: "The process of taking one number away from another.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "multiplication", hint: "Repeated addition of the same number.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "division", hint: "Splitting into equal parts or groups.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "sum", hint: "The result of adding numbers together.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "difference", hint: "The result of subtracting one number from another.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "product", hint: "The result of multiplying numbers.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "quotient", hint: "The result of dividing one number by another.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "equals", hint: "Having the same value or amount.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "plus", hint: "The symbol or operation for addition.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "minus", hint: "The symbol or operation for subtraction.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "times", hint: "Another word for multiplication.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "divided by", hint: "The operation that splits a number into equal parts.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "remainder", hint: "The amount left over after division.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "addend", hint: "A number being added to another number.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "minuend", hint: "The number from which another number is subtracted.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "subtrahend", hint: "The number being subtracted from another.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "factor", hint: "A number that divides another number exactly.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "dividend", hint: "The number being divided.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "divisor", hint: "The number by which another is divided.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "add", hint: "To combine numbers into a sum.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "total", hint: "The final sum or whole amount.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "count", hint: "To determine the total number of units.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "altogether", hint: "A word indicating addition of multiple groups.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "combine", hint: "To put numbers or groups together.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "increase", hint: "To become or make larger in number.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "decrease", hint: "To become or make smaller in number.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "take away", hint: "A common phrase for subtraction.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "share", hint: "To divide into equal groups.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "split", hint: "To divide into parts.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "distribute", hint: "To divide and give out in shares.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "repeated addition", hint: "The conceptual foundation of multiplication.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "equal groups", hint: "Groups with the same number of items, key to multiplication.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "array", hint: "An arrangement of objects in rows and columns, representing multiplication.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "repeated subtraction", hint: "The conceptual foundation of division.", level: "easy", topic: "Basic Arithmetic Operations" },
  { word: "commutative property", hint: "The order of numbers does not change the sum or product.", level: "medium", topic: "Basic Arithmetic Operations" },
  { word: "associative property", hint: "The grouping of numbers does not change the sum or product.", level: "medium", topic: "Basic Arithmetic Operations" },
  { word: "distributive property", hint: "Multiplying a number by a sum is the same as doing each multiplication separately.", level: "medium", topic: "Basic Arithmetic Operations" },
  { word: "identity property", hint: "Adding zero or multiplying by one leaves a number unchanged.", level: "medium", topic: "Basic Arithmetic Operations" },
  { word: "zero property", hint: "Multiplying a number by zero always gives zero.", level: "medium", topic: "Basic Arithmetic Operations" },
  { word: "inverse operations", hint: "Operations that undo each other, like addition and subtraction.", level: "medium", topic: "Basic Arithmetic Operations" },
  { word: "order of operations", hint: "The set of rules for which calculations are performed first in an expression.", level: "medium", topic: "Basic Arithmetic Operations" },

  // Numbers & Counting
  { word: "number", hint: "A mathematical value used for counting or measuring.", level: "easy", topic: "Numbers & Counting" },
  { word: "counting", hint: "Determining how many objects there are.", level: "easy", topic: "Numbers & Counting" },
  { word: "zero", hint: "The number representing nothing or absence of quantity.", level: "easy", topic: "Numbers & Counting" },
  { word: "one", hint: "The first counting number.", level: "easy", topic: "Numbers & Counting" },
  { word: "whole numbers", hint: "Numbers without fractions or decimals; 0, 1, 2, 3...", level: "easy", topic: "Numbers & Counting" },
  { word: "digits", hint: "The symbols 0-9 used to write numbers.", level: "easy", topic: "Numbers & Counting" },
  { word: "place value", hint: "The value of a digit based on its position in a number.", level: "easy", topic: "Numbers & Counting" },
  { word: "ones", hint: "The place value for single items.", level: "easy", topic: "Numbers & Counting" },
  { word: "tens", hint: "The place value representing groups of ten.", level: "easy", topic: "Numbers & Counting" },
  { word: "hundreds", hint: "The place value representing groups of one hundred.", level: "easy", topic: "Numbers & Counting" },
  { word: "thousands", hint: "The place value representing groups of one thousand.", level: "easy", topic: "Numbers & Counting" },
  { word: "millions", hint: "The place value representing groups of one million.", level: "easy", topic: "Numbers & Counting" },
  { word: "greater than", hint: "A comparison showing one quantity is larger than another.", level: "easy", topic: "Numbers & Counting" },
  { word: "less than", hint: "A comparison showing one quantity is smaller than another.", level: "easy", topic: "Numbers & Counting" },
  { word: "equal to", hint: "Having exactly the same value.", level: "easy", topic: "Numbers & Counting" },
  { word: "even numbers", hint: "Numbers divisible by 2; they end in 0, 2, 4, 6, or 8.", level: "easy", topic: "Numbers & Counting" },
  { word: "odd numbers", hint: "Numbers not divisible by 2; they end in 1, 3, 5, 7, or 9.", level: "easy", topic: "Numbers & Counting" },
  { word: "number line", hint: "A straight line with numbers placed at equal intervals.", level: "easy", topic: "Numbers & Counting" },
  { word: "positive numbers", hint: "Numbers greater than zero.", level: "easy", topic: "Numbers & Counting" },
  { word: "negative numbers", hint: "Numbers less than zero.", level: "easy", topic: "Numbers & Counting" },
  { word: "integer", hint: "A whole number that can be positive, negative, or zero.", level: "easy", topic: "Numbers & Counting" },
  { word: "natural numbers", hint: "Counting numbers starting from 1.", level: "easy", topic: "Numbers & Counting" },
  { word: "rounding", hint: "Approximating a number to a specified place value.", level: "easy", topic: "Numbers & Counting" },
  { word: "estimate", hint: "An approximate calculation or judgment of value.", level: "easy", topic: "Numbers & Counting" },
  { word: "compare", hint: "To examine the difference between numbers or quantities.", level: "easy", topic: "Numbers & Counting" },
  { word: "order", hint: "Arranging numbers from least to greatest or vice versa.", level: "easy", topic: "Numbers & Counting" },
  { word: "dozen", hint: "A group of twelve items.", level: "easy", topic: "Counting Numbers" },
  { word: "score", hint: "A group of twenty items.", level: "easy", topic: "Counting Numbers" },
  { word: "pair", hint: "Two items that are the same or go together.", level: "easy", topic: "Counting Numbers" },
  { word: "triple", hint: "Three times as much or three of something.", level: "easy", topic: "Counting Numbers" },
  { word: "double", hint: "Two times as much or two of something.", level: "easy", topic: "Counting Numbers" },
  { word: "single", hint: "Only one; not multiple.", level: "easy", topic: "Counting Numbers" },
  { word: "couple", hint: "Two items, usually similar or related.", level: "easy", topic: "Counting Numbers" },
  { word: "half dozen", hint: "A group of six items.", level: "easy", topic: "Counting Numbers" },
  { word: "gross", hint: "A group of 144 items (12 dozen).", level: "medium", topic: "Counting Numbers" },
  { word: "decade", hint: "A period of ten years.", level: "medium", topic: "Counting Numbers" },
  { word: "century", hint: "A period of one hundred years.", level: "medium", topic: "Counting Numbers" },
  { word: "millennium", hint: "A period of one thousand years.", level: "medium", topic: "Counting Numbers" },
  { word: "baker's dozen", hint: "Thirteen items instead of twelve.", level: "medium", topic: "Counting Numbers" },
  { word: "fortnight", hint: "A period of two weeks.", level: "medium", topic: "Counting Numbers" },
  { word: "quintuple", hint: "Five times as much or five of something.", level: "medium", topic: "Counting Numbers" },
  { word: "sextuple", hint: "Six times as much or six of something.", level: "medium", topic: "Counting Numbers" },
  { word: "octuple", hint: "Eight times as much or eight of something.", level: "medium", topic: "Counting Numbers" },
  { word: "googol", hint: "The number 1 followed by 100 zeros.", level: "hard", topic: "Counting Numbers" },
  { word: "googolplex", hint: "The number 1 followed by a googol of zeros.", level: "hard", topic: "Counting Numbers" },
  { word: "myriad", hint: "Ten thousand or a countless number.", level: "hard", topic: "Counting Numbers" },
  { word: "lakh", hint: "One hundred thousand (100,000).", level: "hard", topic: "Counting Numbers" },
  { word: "crore", hint: "Ten million (10,000,000).", level: "hard", topic: "Counting Numbers" },
  { word: "great gross", hint: "Twelve gross (1,728 items).", level: "hard", topic: "Counting Numbers" },
  { word: "small gross", hint: "Ten dozen (120 items).", level: "hard", topic: "Counting Numbers" },
  { word: "quintillion", hint: "1 followed by 18 zeros.", level: "hard", topic: "Counting Numbers" },
  { word: "sextillion", hint: "1 followed by 21 zeros.", level: "hard", topic: "Counting Numbers" },
  { word: "nonillion", hint: "1 followed by 30 zeros.", level: "hard", topic: "Counting Numbers" },

  // Fractions & Decimals
  { word: "fraction", hint: "A part of a whole, written as one number over another.", level: "easy", topic: "Fractions & Decimals" },
  { word: "numerator", hint: "The top number in a fraction showing how many parts are taken.", level: "easy", topic: "Fractions & Decimals" },
  { word: "denominator", hint: "The bottom number in a fraction showing total equal parts.", level: "easy", topic: "Fractions & Decimals" },
  { word: "unit fraction", hint: "A fraction with numerator 1, such as 1/2 or 1/3.", level: "easy", topic: "Fractions & Decimals" },
  { word: "proper fraction", hint: "A fraction where the numerator is less than the denominator.", level: "easy", topic: "Fractions & Decimals" },
  { word: "improper fraction", hint: "A fraction where the numerator is greater than or equal to the denominator.", level: "easy", topic: "Fractions & Decimals" },
  { word: "mixed number", hint: "A whole number combined with a fraction.", level: "easy", topic: "Fractions & Decimals" },
  { word: "equivalent fractions", hint: "Different fractions that represent the same value.", level: "easy", topic: "Fractions & Decimals" },
  { word: "simplest form", hint: "A fraction where numerator and denominator have no common factors except 1.", level: "easy", topic: "Fractions & Decimals" },
  { word: "decimal", hint: "A number that uses a decimal point to show parts of a whole.", level: "easy", topic: "Fractions & Decimals" },
  { word: "decimal point", hint: "The dot separating the whole number from fractional parts.", level: "easy", topic: "Fractions & Decimals" },
  { word: "tenths", hint: "The first decimal place to the right of the decimal point.", level: "easy", topic: "Fractions & Decimals" },
  { word: "hundredths", hint: "The second decimal place to the right of the decimal point.", level: "easy", topic: "Fractions & Decimals" },
  { word: "thousandths", hint: "The third decimal place to the right of the decimal point.", level: "easy", topic: "Fractions & Decimals" },
  { word: "half", hint: "One of two equal parts; 1/2.", level: "easy", topic: "Fractions & Decimals" },
  { word: "third", hint: "One of three equal parts; 1/3.", level: "easy", topic: "Fractions & Decimals" },
  { word: "quarter", hint: "One of four equal parts; 1/4.", level: "easy", topic: "Fractions & Decimals" },
  { word: "reduce", hint: "To simplify a fraction to its lowest terms.", level: "easy", topic: "Fractions & Decimals" },
  { word: "common denominator", hint: "A shared denominator for two or more fractions.", level: "easy", topic: "Fractions & Decimals" },
  { word: "like fractions", hint: "Fractions that have the same denominator.", level: "easy", topic: "Fractions & Decimals" },

  // Basic Geometry
  { word: "shape", hint: "The form or outline of an object.", level: "easy", topic: "Basic Geometry" },
  { word: "triangle", hint: "A polygon with three sides and three angles.", level: "easy", topic: "Basic Geometry" },
  { word: "square", hint: "A quadrilateral with four equal sides and four right angles.", level: "easy", topic: "Basic Geometry" },
  { word: "rectangle", hint: "A quadrilateral with four right angles and opposite sides equal.", level: "easy", topic: "Basic Geometry" },
  { word: "circle", hint: "A round shape where all points are equidistant from the center.", level: "easy", topic: "Basic Geometry" },
  { word: "oval", hint: "An elongated circle shape.", level: "easy", topic: "Basic Geometry" },
  { word: "pentagon", hint: "A polygon with five sides.", level: "easy", topic: "Basic Geometry" },
  { word: "hexagon", hint: "A polygon with six sides.", level: "easy", topic: "Basic Geometry" },
  { word: "octagon", hint: "A polygon with eight sides.", level: "easy", topic: "Basic Geometry" },
  { word: "cube", hint: "A 3D shape with six square faces.", level: "easy", topic: "Basic Geometry" },
  { word: "sphere", hint: "A perfectly round 3D object like a ball.", level: "easy", topic: "Basic Geometry" },
  { word: "cone", hint: "A 3D shape with a circular base and pointed top.", level: "easy", topic: "Basic Geometry" },
  { word: "cylinder", hint: "A 3D shape with two parallel circular bases.", level: "easy", topic: "Basic Geometry" },
  { word: "pyramid", hint: "A 3D shape with a polygon base and triangular sides meeting at a point.", level: "easy", topic: "Basic Geometry" },
  { word: "edge", hint: "The line where two faces of a solid meet.", level: "easy", topic: "Basic Geometry" },
  { word: "face", hint: "A flat surface of a solid shape.", level: "easy", topic: "Basic Geometry" },
  { word: "vertex", hint: "A corner point where edges meet.", level: "easy", topic: "Basic Geometry" },
  { word: "side", hint: "A line segment forming part of a polygon.", level: "easy", topic: "Basic Geometry" },
  { word: "corner", hint: "The point where two sides meet.", level: "easy", topic: "Basic Geometry" },
  { word: "line", hint: "A straight path extending in both directions infinitely.", level: "easy", topic: "Basic Geometry" },
  { word: "point", hint: "An exact location in space with no size.", level: "easy", topic: "Basic Geometry" },
  { word: "ray", hint: "A line with one endpoint extending infinitely in one direction.", level: "easy", topic: "Basic Geometry" },
  { word: "line segment", hint: "A part of a line with two endpoints.", level: "easy", topic: "Basic Geometry" },
  { word: "curve", hint: "A smoothly flowing line that is not straight.", level: "easy", topic: "Basic Geometry" },
  { word: "symmetry", hint: "When one half of a shape is a mirror image of the other half.", level: "easy", topic: "Basic Geometry" },
  { word: "line of symmetry", hint: "A line dividing a shape into two identical halves.", level: "easy", topic: "Basic Geometry" },
  { word: "congruent", hint: "Having the same shape and size.", level: "easy", topic: "Basic Geometry" },

  // Measurement
  { word: "measure", hint: "To find the size, length, or amount of something.", level: "easy", topic: "Measurement" },
  { word: "length", hint: "The measurement of something from end to end.", level: "easy", topic: "Measurement" },
  { word: "width", hint: "The measurement from side to side.", level: "easy", topic: "Measurement" },
  { word: "height", hint: "The measurement from bottom to top.", level: "easy", topic: "Measurement" },
  { word: "perimeter", hint: "The distance around the outside of a shape.", level: "easy", topic: "Measurement" },
  { word: "area", hint: "The amount of space inside a 2D shape.", level: "easy", topic: "Measurement" },
  { word: "volume", hint: "The amount of space occupied by a 3D object.", level: "easy", topic: "Measurement" },
  { word: "capacity", hint: "The amount a container can hold.", level: "easy", topic: "Measurement" },
  { word: "weight", hint: "How heavy something is.", level: "easy", topic: "Measurement" },
  { word: "mass", hint: "The amount of matter in an object.", level: "easy", topic: "Measurement" },
  { word: "time", hint: "The ongoing sequence of events measured in hours, minutes, and seconds.", level: "easy", topic: "Measurement" },
  { word: "temperature", hint: "How hot or cold something is.", level: "easy", topic: "Measurement" },
  { word: "distance", hint: "The amount of space between two points.", level: "easy", topic: "Measurement" },
  { word: "meter", hint: "The basic unit of length in the metric system.", level: "easy", topic: "Measurement" },
  { word: "centimeter", hint: "One hundredth of a meter.", level: "easy", topic: "Measurement" },
  { word: "millimeter", hint: "One thousandth of a meter.", level: "easy", topic: "Measurement" },
  { word: "kilometer", hint: "One thousand meters.", level: "easy", topic: "Measurement" },
  { word: "inch", hint: "A unit of length in the imperial system.", level: "easy", topic: "Measurement" },
  { word: "foot", hint: "A unit of length equal to 12 inches.", level: "easy", topic: "Measurement" },
  { word: "yard", hint: "A unit of length equal to 3 feet.", level: "easy", topic: "Measurement" },
  { word: "mile", hint: "A unit of length equal to 5,280 feet.", level: "easy", topic: "Measurement" },
  { word: "gram", hint: "A basic unit of mass in the metric system.", level: "easy", topic: "Measurement" },
  { word: "kilogram", hint: "One thousand grams.", level: "easy", topic: "Measurement" },
  { word: "liter", hint: "A basic unit of volume in the metric system.", level: "easy", topic: "Measurement" },
  { word: "milliliter", hint: "One thousandth of a liter.", level: "easy", topic: "Measurement" },
  { word: "ounce", hint: "A unit of weight in the imperial system.", level: "easy", topic: "Measurement" },
  { word: "pound", hint: "A unit of weight equal to 16 ounces.", level: "easy", topic: "Measurement" },
  { word: "cup", hint: "A unit of volume used in cooking.", level: "easy", topic: "Measurement" },
  { word: "pint", hint: "A unit of volume equal to 2 cups.", level: "easy", topic: "Measurement" },
  { word: "quart", hint: "A unit of volume equal to 2 pints.", level: "easy", topic: "Measurement" },
  { word: "gallon", hint: "A unit of volume equal to 4 quarts.", level: "easy", topic: "Measurement" },

  // Time & Money
  { word: "hour", hint: "A unit of time equal to 60 minutes.", level: "easy", topic: "Time & Money" },
  { word: "minute", hint: "A unit of time equal to 60 seconds.", level: "easy", topic: "Time & Money" },
  { word: "second", hint: "The basic unit of time.", level: "easy", topic: "Time & Money" },
  { word: "clock", hint: "An instrument for measuring and showing time.", level: "easy", topic: "Time & Money" },
  { word: "calendar", hint: "A chart showing days, weeks, and months of a year.", level: "easy", topic: "Time & Money" },
  { word: "money", hint: "Currency used to buy goods and services.", level: "easy", topic: "Time & Money" },
  { word: "dollar", hint: "The basic unit of currency in the United States.", level: "easy", topic: "Time & Money" },
  { word: "cent", hint: "One hundredth of a dollar.", level: "easy", topic: "Time & Money" },
  { word: "penny", hint: "A coin worth one cent.", level: "easy", topic: "Time & Money" },
  { word: "nickel", hint: "A coin worth five cents.", level: "easy", topic: "Time & Money" },
  { word: "dime", hint: "A coin worth ten cents.", level: "easy", topic: "Time & Money" },
  { word: "quarter", hint: "A coin worth twenty-five cents.", level: "easy", topic: "Time & Money" },
  { word: "change", hint: "Money returned when payment exceeds the cost.", level: "easy", topic: "Time & Money" },
  { word: "cost", hint: "The amount of money needed to buy something.", level: "easy", topic: "Time & Money" },

  // Patterns & Sequences
  { word: "pattern", hint: "A repeated design or sequence.", level: "easy", topic: "Patterns & Sequences" },
  { word: "sequence", hint: "An ordered list following a rule.", level: "easy", topic: "Patterns & Sequences" },
  { word: "skip counting", hint: "Counting by numbers other than 1.", level: "easy", topic: "Patterns & Sequences" },
  { word: "repeating pattern", hint: "A pattern that continues in the same way.", level: "easy", topic: "Patterns & Sequences" },
  { word: "growing pattern", hint: "A pattern that increases by a fixed amount.", level: "easy", topic: "Patterns & Sequences" },
  { word: "rule", hint: "A statement describing a mathematical relationship.", level: "easy", topic: "Patterns & Sequences" },

  // Data & Graphs
  { word: "graph", hint: "A visual representation of data.", level: "easy", topic: "Data & Graphs" },
  { word: "chart", hint: "A visual display of information.", level: "easy", topic: "Data & Graphs" },
  { word: "bar graph", hint: "A graph using bars to show data.", level: "easy", topic: "Data & Graphs" },
  { word: "picture graph", hint: "A graph using pictures to represent data.", level: "easy", topic: "Data & Graphs" },
  { word: "line plot", hint: "A graph showing data points along a number line.", level: "easy", topic: "Data & Graphs" },
  { word: "tally", hint: "Marks used to count items.", level: "easy", topic: "Data & Graphs" },
  { word: "data", hint: "Information collected for analysis.", level: "easy", topic: "Data & Graphs" },
  { word: "survey", hint: "Collecting information by asking questions.", level: "easy", topic: "Data & Graphs" },
  { word: "table", hint: "An organized arrangement of data in rows and columns.", level: "easy", topic: "Data & Graphs" },
  { word: "label", hint: "Text identifying parts of a graph or diagram.", level: "easy", topic: "Data & Graphs" },
  { word: "title", hint: "The name of a graph or chart.", level: "easy", topic: "Data & Graphs" },
  { word: "scale", hint: "The range of values on a graph axis.", level: "easy", topic: "Data & Graphs" },

  // Problem Solving
  { word: "problem", hint: "A question requiring a solution.", level: "easy", topic: "Problem Solving" },
  { word: "solve", hint: "To find the answer to a problem.", level: "easy", topic: "Problem Solving" },
  { word: "solution", hint: "The answer to a problem.", level: "easy", topic: "Problem Solving" },
  { word: "strategy", hint: "A plan for solving a problem.", level: "easy", topic: "Problem Solving" },
  { word: "guess and check", hint: "A strategy of trying answers until finding the correct one.", level: "easy", topic: "Problem Solving" },
  { word: "work backward", hint: "Starting from the end result to find the beginning.", level: "easy", topic: "Problem Solving" },
  { word: "draw a picture", hint: "Using a visual representation to solve a problem.", level: "easy", topic: "Problem Solving" },
  { word: "make a list", hint: "Writing out possibilities to organize thinking.", level: "easy", topic: "Problem Solving" },
  { word: "find a pattern", hint: "Looking for repeating relationships in numbers.", level: "easy", topic: "Problem Solving" },
  { word: "word problem", hint: "A math problem presented in written form.", level: "easy", topic: "Problem Solving" },
  { word: "operation", hint: "A mathematical process like addition or subtraction.", level: "easy", topic: "Problem Solving" },
  { word: "inverse operation", hint: "The opposite operation that undoes another.", level: "easy", topic: "Problem Solving" },
  { word: "reasonable", hint: "Making sense or being logical.", level: "easy", topic: "Problem Solving" },
  { word: "check", hint: "To verify an answer is correct.", level: "easy", topic: "Problem Solving" },

  // Mathematical Properties & Relationships
  { word: "property", hint: "A characteristic or attribute of mathematical objects.", level: "medium", topic: "Mathematical Properties & Relationships" },
  { word: "relationship", hint: "How two or more mathematical objects are connected.", level: "medium", topic: "Mathematical Properties & Relationships" },
  { word: "equivalence", hint: "The state of being equal in value or meaning.", level: "medium", topic: "Mathematical Properties & Relationships" },
  { word: "proportional", hint: "Having a constant ratio between corresponding values.", level: "medium", topic: "Mathematical Properties & Relationships" },
  { word: "inverse", hint: "Opposite or reverse relationship.", level: "medium", topic: "Mathematical Properties & Relationships" },
  { word: "direct variation", hint: "When two quantities increase or decrease together at constant rate.", level: "medium", topic: "Mathematical Properties & Relationships" },
  { word: "inverse variation", hint: "When one quantity increases as the other decreases.", level: "medium", topic: "Mathematical Properties & Relationships" },

  // Algebra Basics
  { word: "algebra", hint: "Branch of mathematics using symbols and letters to represent numbers.", level: "medium", topic: "Algebra Basics" },
  { word: "variable", hint: "A symbol, usually a letter, that represents an unknown number.", level: "medium", topic: "Algebra Basics" },
  { word: "expression", hint: "A combination of numbers, variables, and operations.", level: "medium", topic: "Algebra Basics" },
  { word: "equation", hint: "A mathematical statement that two expressions are equal.", level: "medium", topic: "Algebra Basics" },
  { word: "inequality", hint: "A mathematical statement comparing expressions that are not equal.", level: "medium", topic: "Algebra Basics" },
  { word: "coefficient", hint: "A number multiplying a variable in an algebraic expression.", level: "medium", topic: "Algebra Basics" },
  { word: "constant", hint: "A fixed value that does not change.", level: "medium", topic: "Algebra Basics" },
  { word: "term", hint: "A single number or variable, or numbers and variables multiplied together.", level: "medium", topic: "Algebra Basics" },
  { word: "like terms", hint: "Terms with the same variable raised to the same power.", level: "medium", topic: "Algebra Basics" },
  { word: "combine like terms", hint: "Adding or subtracting terms with the same variable part.", level: "medium", topic: "Algebra Basics" },
  { word: "simplify", hint: "To reduce an expression to its simplest form.", level: "medium", topic: "Algebra Basics" },
  { word: "evaluate", hint: "To find the numerical value of an expression.", level: "medium", topic: "Algebra Basics" },
  { word: "substitute", hint: "To replace a variable with a number.", level: "medium", topic: "Algebra Basics" },
  { word: "isolate", hint: "To get a variable alone on one side of an equation.", level: "medium", topic: "Algebra Basics" },
  { word: "linear equation", hint: "An equation whose graph is a straight line.", level: "medium", topic: "Algebra Basics" },
  { word: "slope", hint: "The steepness of a line, calculated as rise over run.", level: "medium", topic: "Algebra Basics" },
  { word: "y-intercept", hint: "The point where a line crosses the y-axis.", level: "medium", topic: "Algebra Basics" },
  { word: "x-intercept", hint: "The point where a line crosses the x-axis.", level: "medium", topic: "Algebra Basics" },
  { word: "ordered pair", hint: "Two numbers written in a specific order to locate a point.", level: "medium", topic: "Algebra Basics" },
  { word: "coordinate", hint: "A number representing position on a number line or plane.", level: "medium", topic: "Algebra Basics" },
  { word: "origin", hint: "The point (0,0) where axes intersect on a coordinate plane.", level: "medium", topic: "Algebra Basics" },
  { word: "quadrant", hint: "One of four sections of a coordinate plane.", level: "medium", topic: "Algebra Basics" },
  { word: "system of equations", hint: "Two or more equations with the same variables.", level: "medium", topic: "Algebra Basics" },
  { word: "exponent", hint: "A number showing how many times to multiply a base by itself.", level: "medium", topic: "Algebra Basics" },
  { word: "base", hint: "The number being multiplied by itself in a power.", level: "medium", topic: "Algebra Basics" },
  { word: "power", hint: "A number expressed using a base and exponent.", level: "medium", topic: "Algebra Basics" },
  { word: "square", hint: "To multiply a number by itself.", level: "medium", topic: "Algebra Basics" },
  { word: "square root", hint: "A number that when multiplied by itself gives the original number.", level: "medium", topic: "Algebra Basics" },
  { word: "cube", hint: "To multiply a number by itself three times.", level: "medium", topic: "Algebra Basics" },
  { word: "cube root", hint: "A number that when cubed gives the original number.", level: "medium", topic: "Algebra Basics" },

  // Ratios, Proportions & Percentages
  { word: "ratio", hint: "A comparison of two quantities by division.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "rate", hint: "A ratio comparing different types of quantities.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "unit rate", hint: "A rate with a denominator of 1.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "proportion", hint: "An equation stating that two ratios are equal.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "cross multiply", hint: "Multiplying diagonally across an equation to solve proportions.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "percent", hint: "A ratio expressed as a fraction of 100.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "percentage", hint: "An amount expressed as parts per hundred.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "discount", hint: "A reduction in price.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "markup", hint: "An increase added to a cost.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "sales tax", hint: "A percentage added to the cost of goods.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "tip", hint: "An amount of money given as a percentage of a bill.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "commission", hint: "Payment based on a percentage of sales.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "interest", hint: "Money paid for borrowing or earned from saving.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "principal", hint: "The original amount of money borrowed or invested.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "simple interest", hint: "Interest calculated only on the principal.", level: "medium", topic: "Ratios, Proportions & Percentages" },
  { word: "compound interest", hint: "Interest calculated on principal and accumulated interest.", level: "medium", topic: "Ratios, Proportions & Percentages" },

  // Number Theory & Properties
  { word: "prime number", hint: "A number greater than 1 with exactly two factors: 1 and itself.", level: "medium", topic: "Number Theory & Properties" },
  { word: "composite number", hint: "A number with more than two factors.", level: "medium", topic: "Number Theory & Properties" },
  { word: "prime factorization", hint: "Expressing a number as a product of its prime factors.", level: "medium", topic: "Number Theory & Properties" },
  { word: "multiple", hint: "A number that can be divided by another number without remainder.", level: "medium", topic: "Number Theory & Properties" },
  { word: "common multiple", hint: "A multiple shared by two or more numbers.", level: "medium", topic: "Number Theory & Properties" },
  { word: "least common multiple", hint: "The smallest multiple common to two or more numbers.", level: "medium", topic: "Number Theory & Properties" },
  { word: "greatest common factor", hint: "The largest factor shared by two or more numbers.", level: "medium", topic: "Number Theory & Properties" },
  { word: "divisibility rule", hint: "A shortcut to determine if one number divides another evenly.", level: "medium", topic: "Number Theory & Properties" },
  { word: "absolute value", hint: "The distance of a number from zero on a number line.", level: "medium", topic: "Number Theory & Properties" },
  { word: "opposite", hint: "A number the same distance from zero but on the opposite side.", level: "medium", topic: "Number Theory & Properties" },
  { word: "reciprocal", hint: "The inverse of a fraction, obtained by swapping numerator and denominator.", level: "medium", topic: "Number Theory & Properties" },
  { word: "rational number", hint: "A number that can be expressed as a fraction.", level: "medium", topic: "Number Theory & Properties" },
  { word: "irrational number", hint: "A number that cannot be expressed as a simple fraction.", level: "medium", topic: "Number Theory & Properties" },
  { word: "real number", hint: "Any rational or irrational number.", level: "medium", topic: "Number Theory & Properties" },

  // Geometry - Angles & Lines
  { word: "angle", hint: "The figure formed by two rays sharing a common endpoint.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "acute angle", hint: "An angle measuring less than 90 degrees.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "right angle", hint: "An angle measuring exactly 90 degrees.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "obtuse angle", hint: "An angle measuring more than 90 but less than 180 degrees.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "straight angle", hint: "An angle measuring exactly 180 degrees.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "reflex angle", hint: "An angle measuring more than 180 degrees but less than 360.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "complementary angles", hint: "Two angles whose measures add up to 90 degrees.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "supplementary angles", hint: "Two angles whose measures add up to 180 degrees.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "adjacent angles", hint: "Angles that share a common vertex and side.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "vertical angles", hint: "Opposite angles formed by intersecting lines.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "parallel lines", hint: "Lines in the same plane that never intersect.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "perpendicular lines", hint: "Lines that intersect at right angles.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "intersecting lines", hint: "Lines that cross at a point.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "transversal", hint: "A line that crosses two or more parallel lines.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "corresponding angles", hint: "Angles in the same position at different intersections.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "alternate interior angles", hint: "Interior angles on opposite sides of a transversal.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "bisect", hint: "To divide into two equal parts.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "angle bisector", hint: "A ray dividing an angle into two equal angles.", level: "medium", topic: "Geometry - Angles & Lines" },
  { word: "midpoint", hint: "The point exactly halfway between two endpoints.", level: "medium", topic: "Geometry - Angles & Lines" },

  // Geometry - Polygons & Circles
  { word: "polygon", hint: "A closed shape with straight sides.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "regular polygon", hint: "A polygon with all sides and angles equal.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "irregular polygon", hint: "A polygon with sides or angles that are not all equal.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "quadrilateral", hint: "A polygon with four sides.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "parallelogram", hint: "A quadrilateral with opposite sides parallel.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "trapezoid", hint: "A quadrilateral with at least one pair of parallel sides.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "rhombus", hint: "A parallelogram with all sides equal.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "kite", hint: "A quadrilateral with two pairs of adjacent equal sides.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "diagonal", hint: "A line segment connecting non-adjacent vertices.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "interior angle", hint: "An angle inside a polygon.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "exterior angle", hint: "An angle outside a polygon formed by extending a side.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "sum of angles", hint: "The total of all angles in a polygon.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "radius", hint: "A line from the center to any point on a circle.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "diameter", hint: "A line through the center of a circle touching two points on circumference.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "circumference", hint: "The distance around a circle.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "pi", hint: "The ratio of a circle's circumference to its diameter, approximately 3.14159.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "chord", hint: "A line segment connecting two points on a circle.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "arc", hint: "A portion of the circumference of a circle.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "semicircle", hint: "Half of a circle.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "sector", hint: "A pie-shaped portion of a circle.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "tangent", hint: "A line that touches a circle at exactly one point.", level: "medium", topic: "Geometry - Polygons & Circles" },
  { word: "central angle", hint: "An angle with vertex at the center of a circle.", level: "medium", topic: "Geometry - Polygons & Circles" },

  // 3D Geometry & Measurement
  { word: "prism", hint: "A 3D shape with two parallel congruent bases.", level: "medium", topic: "3D Geometry & Measurement" },
  { word: "rectangular prism", hint: "A prism with rectangular bases.", level: "medium", topic: "3D Geometry & Measurement" },
  { word: "triangular prism", hint: "A prism with triangular bases.", level: "medium", topic: "3D Geometry & Measurement" },
  { word: "surface area", hint: "The total area of all surfaces of a 3D shape.", level: "medium", topic: "3D Geometry & Measurement" },
  { word: "lateral surface area", hint: "The surface area excluding the bases.", level: "medium", topic: "3D Geometry & Measurement" },
  { word: "net", hint: "A flat pattern that folds into a 3D shape.", level: "medium", topic: "3D Geometry & Measurement" },
  { word: "cross section", hint: "The shape formed by slicing through a 3D object.", level: "medium", topic: "3D Geometry & Measurement" },

  // Statistics & Probability
  { word: "statistics", hint: "The study of collecting, analyzing, and interpreting data.", level: "medium", topic: "Statistics & Probability" },
  { word: "data set", hint: "A collection of numbers or values.", level: "medium", topic: "Statistics & Probability" },
  { word: "mean", hint: "The average of a set of numbers.", level: "medium", topic: "Statistics & Probability" },
  { word: "median", hint: "The middle value in a sorted list of numbers.", level: "medium", topic: "Statistics & Probability" },
  { word: "mode", hint: "The value that appears most frequently in a data set.", level: "medium", topic: "Statistics & Probability" },
  { word: "range", hint: "The difference between the highest and lowest values.", level: "medium", topic: "Statistics & Probability" },
  { word: "outlier", hint: "A value much higher or lower than other values in a set.", level: "medium", topic: "Statistics & Probability" },
  { word: "frequency", hint: "How often a value occurs in a data set.", level: "medium", topic: "Statistics & Probability" },
  { word: "frequency table", hint: "A table showing how often each value appears.", level: "medium", topic: "Statistics & Probability" },
  { word: "histogram", hint: "A bar graph showing frequency distribution.", level: "medium", topic: "Statistics & Probability" },
  { word: "line graph", hint: "A graph using points connected by lines to show change over time.", level: "medium", topic: "Statistics & Probability" },
  { word: "scatter plot", hint: "A graph showing the relationship between two variables.", level: "medium", topic: "Statistics & Probability" },
  { word: "correlation", hint: "A measure of how two variables change together.", level: "medium", topic: "Statistics & Probability" },
  { word: "probability", hint: "The measure of how likely an event is to occur.", level: "medium", topic: "Statistics & Probability" },
  { word: "outcome", hint: "A possible result of an experiment.", level: "medium", topic: "Statistics & Probability" },
  { word: "event", hint: "A set of outcomes from an experiment.", level: "medium", topic: "Statistics & Probability" },
  { word: "sample space", hint: "The set of all possible outcomes.", level: "medium", topic: "Statistics & Probability" },
  { word: "theoretical probability", hint: "Probability based on reasoning about outcomes.", level: "medium", topic: "Statistics & Probability" },
  { word: "experimental probability", hint: "Probability based on actual experiments.", level: "medium", topic: "Statistics & Probability" },
  { word: "tree diagram", hint: "A diagram showing all possible outcomes.", level: "medium", topic: "Statistics & Probability" },
  { word: "combination", hint: "A selection of items where order does not matter.", level: "medium", topic: "Statistics & Probability" },
  { word: "permutation", hint: "An arrangement of items where order matters.", level: "medium", topic: "Statistics & Probability" },

  // Functions & Relations
  { word: "function", hint: "A relation where each input has exactly one output.", level: "medium", topic: "Functions & Relations" },
  { word: "domain", hint: "The set of all possible input values for a function.", level: "medium", topic: "Functions & Relations" },
  { word: "range", hint: "The set of all possible output values of a function.", level: "medium", topic: "Functions & Relations" },
  { word: "input", hint: "The value put into a function.", level: "medium", topic: "Functions & Relations" },
  { word: "output", hint: "The value that comes out of a function.", level: "medium", topic: "Functions & Relations" },
  { word: "function notation", hint: "Using f(x) to represent a function.", level: "medium", topic: "Functions & Relations" },
  { word: "linear function", hint: "A function whose graph is a straight line.", level: "medium", topic: "Functions & Relations" },
  { word: "quadratic function", hint: "A function of the form f(x) = ax² + bx + c.", level: "medium", topic: "Functions & Relations" },
  { word: "parabola", hint: "The U-shaped graph of a quadratic function.", level: "medium", topic: "Functions & Relations" },
  { word: "vertex", hint: "The highest or lowest point on a parabola.", level: "medium", topic: "Functions & Relations" },
  { word: "axis of symmetry", hint: "A line dividing a parabola into mirror images.", level: "medium", topic: "Functions & Relations" },

  // Transformations
  { word: "transformation", hint: "Changing a figure's position or size.", level: "medium", topic: "Transformations" },
  { word: "translation", hint: "Sliding a figure without turning or flipping.", level: "medium", topic: "Transformations" },
  { word: "reflection", hint: "Flipping a figure over a line.", level: "medium", topic: "Transformations" },
  { word: "rotation", hint: "Turning a figure around a point.", level: "medium", topic: "Transformations" },
  { word: "dilation", hint: "Enlarging or reducing a figure proportionally.", level: "medium", topic: "Transformations" },
  { word: "scale factor", hint: "The ratio of corresponding lengths in similar figures.", level: "medium", topic: "Transformations" },
  { word: "similar", hint: "Figures that have the same shape but not necessarily the same size.", level: "medium", topic: "Transformations" },

  // Advanced Algebra
  { word: "polynomial", hint: "An expression with multiple terms involving variables and exponents.", level: "hard", topic: "Advanced Algebra" },
  { word: "monomial", hint: "A polynomial with one term.", level: "hard", topic: "Advanced Algebra" },
  { word: "binomial", hint: "A polynomial with two terms.", level: "hard", topic: "Advanced Algebra" },
  { word: "trinomial", hint: "A polynomial with three terms.", level: "hard", topic: "Advanced Algebra" },
  { word: "degree", hint: "The highest exponent in a polynomial.", level: "hard", topic: "Advanced Algebra" },
  { word: "leading coefficient", hint: "The coefficient of the term with the highest degree.", level: "hard", topic: "Advanced Algebra" },
  { word: "synthetic division", hint: "A shortcut method for dividing polynomials.", level: "hard", topic: "Advanced Algebra" },
  { word: "remainder theorem", hint: "If a polynomial f(x) is divided by (x-c), the remainder is f(c).", level: "hard", topic: "Advanced Algebra" },
  { word: "factor theorem", hint: "x-c is a factor of f(x) if and only if f(c)=0.", level: "hard", topic: "Advanced Algebra" },
  { word: "rational root theorem", hint: "Helps find possible rational roots of a polynomial.", level: "hard", topic: "Advanced Algebra" },
  { word: "complex number", hint: "A number with real and imaginary parts.", level: "hard", topic: "Advanced Algebra" },
  { word: "imaginary number", hint: "A number that when squared gives a negative result.", level: "hard", topic: "Advanced Algebra" },
  { word: "complex conjugate", hint: "A complex number with the same real part but opposite imaginary part.", level: "hard", topic: "Advanced Algebra" },

  // Quadratic Equations & Functions
  { word: "quadratic equation", hint: "An equation of the form ax² + bx + c = 0.", level: "hard", topic: "Quadratic Equations & Functions" },
  { word: "quadratic formula", hint: "x = [-b ± √(b²-4ac)] / 2a used to solve quadratic equations.", level: "hard", topic: "Quadratic Equations & Functions" },
  { word: "discriminant", hint: "b²-4ac, determines the nature of quadratic roots.", level: "hard", topic: "Quadratic Equations & Functions" },
  { word: "completing the square", hint: "A method for solving quadratic equations.", level: "hard", topic: "Quadratic Equations & Functions" },
  { word: "vertex form", hint: "f(x) = a(x-h)² + k, shows vertex of parabola.", level: "hard", topic: "Quadratic Equations & Functions" },
  { word: "focus", hint: "A fixed point used to define a parabola.", level: "hard", topic: "Quadratic Equations & Functions" },
  { word: "directrix", hint: "A fixed line used to define a parabola.", level: "hard", topic: "Quadratic Equations & Functions" },

  // Exponential & Logarithmic Functions
  { word: "exponential function", hint: "A function where the variable is in the exponent.", level: "hard", topic: "Exponential & Logarithmic Functions" },
  { word: "logarithm", hint: "The exponent to which a base must be raised to produce a given number.", level: "hard", topic: "Exponential & Logarithmic Functions" },
  { word: "natural logarithm", hint: "Logarithm with base e.", level: "hard", topic: "Exponential & Logarithmic Functions" },
  { word: "common logarithm", hint: "Logarithm with base 10.", level: "hard", topic: "Exponential & Logarithmic Functions" },
  { word: "logarithmic function", hint: "The inverse of an exponential function.", level: "hard", topic: "Exponential & Logarithmic Functions" },
  { word: "exponential growth", hint: "Growth at a rate proportional to current value.", level: "hard", topic: "Exponential & Logarithmic Functions" },
  { word: "exponential decay", hint: "Decrease at a rate proportional to current value.", level: "hard", topic: "Exponential & Logarithmic Functions" },
  { word: "half-life", hint: "Time for a quantity to reduce to half its initial value.", level: "hard", topic: "Exponential & Logarithmic Functions" },

// Trigonometry
  { "word": "trigonometry", "hint": "Mathematical field derived from Greek words for 'triangle' and 'measure'.", "level": "hard", "topic": "Trigonometry" },
  { "word": "sine", "hint": "In a right triangle, this function equals opposite/hypotenuse. Graph starts at origin (0,0).", "level": "hard", "topic": "Trigonometry" },
  { "word": "cosine", "hint": "In a right triangle, this function equals adjacent/hypotenuse. Graph starts at maximum value (0,1).", "level": "hard", "topic": "Trigonometry" },
  { "word": "tangent", "hint": "In a right triangle, this function equals opposite/adjacent. Has vertical asymptotes every π radians.", "level": "hard", "topic": "Trigonometry" },
  { "word": "cosecant", "hint": "Reciprocal of sine function. Equals hypotenuse/opposite in right triangles.", "level": "hard", "topic": "Trigonometry" },
  { "word": "secant", "hint": "Reciprocal of cosine function. Equals hypotenuse/adjacent in right triangles.", "level": "hard", "topic": "Trigonometry" },
  { "word": "cotangent", "hint": "Reciprocal of tangent function. Equals adjacent/opposite in right triangles.", "level": "hard", "topic": "Trigonometry" },
  { "word": "unit circle", "hint": "Circle with radius 1 where x=cos(θ) and y=sin(θ). Used to define trig functions for all angles.", "level": "hard", "topic": "Trigonometry" },
  { "word": "radian", "hint": "Angle measure where 180° equals π of these units. Defined as arc length divided by radius.", "level": "hard", "topic": "Trigonometry" },
  { "word": "amplitude", "hint": "For y=Asin(Bx) or y=Acos(Bx), this is |A| - half the distance between maximum and minimum values.", "level": "hard", "topic": "Trigonometry" },
  { "word": "period", "hint": "For y=sin(Bx) or y=cos(Bx), this equals 2π/B - the horizontal distance to complete one full cycle.", "level": "hard", "topic": "Trigonometry" },
  { "word": "frequency", "hint": "For trig functions, equals 1/period. Number of complete cycles in 2π radians.", "level": "hard", "topic": "Trigonometry" },
  { "word": "phase shift", "hint": "Horizontal translation in equations like y=sin(x-C). Moves graph left or right.", "level": "hard", "topic": "Trigonometry" },
  { "word": "trigonometric identity", "hint": "Equations like sin²θ+cos²θ=1 that are true for all values of the variable.", "level": "hard", "topic": "Trigonometry" },
  { "word": "pythagorean identity", "hint": "Fundamental identity: sin²θ + cos²θ = 1. Derived from Pythagorean theorem applied to unit circle.", "level": "hard", "topic": "Trigonometry" },
  { "word": "double angle formula", "hint": "Identities including sin(2θ)=2sinθcosθ and cos(2θ)=cos²θ-sin²θ.", "level": "hard", "topic": "Trigonometry" },
  { "word": "law of sines", "hint": "a/sinA = b/sinB = c/sinC. Used when you know two angles and one side, or two sides and a non-included angle.", "level": "hard", "topic": "Trigonometry" },
  { "word": "law of cosines", "hint": "c² = a² + b² - 2ab·cosC. Generalization of Pythagorean theorem for non-right triangles.", "level": "hard", "topic": "Trigonometry" },
  
  // Advanced Geometry
  { word: "conic sections", hint: "Curves formed by intersecting a plane with a cone.", level: "hard", topic: "Advanced Geometry" },
  { word: "ellipse", hint: "Set of points where sum of distances to two foci is constant.", level: "hard", topic: "Advanced Geometry" },
  { word: "hyperbola", hint: "Set of points where difference of distances to two foci is constant.", level: "hard", topic: "Advanced Geometry" },
  { word: "locus", hint: "Set of points satisfying given conditions.", level: "hard", topic: "Advanced Geometry" },
  { word: "inscribed angle", hint: "Angle with vertex on a circle and sides containing chords.", level: "hard", topic: "Advanced Geometry" },
  { word: "circumscribed", hint: "A figure drawn around another, touching it at points.", level: "hard", topic: "Advanced Geometry" },
  { word: "inscribed", hint: "A figure drawn inside another, touching it at points.", level: "hard", topic: "Advanced Geometry" },
  { word: "apothem", hint: "Distance from center to midpoint of a side in regular polygon.", level: "hard", topic: "Advanced Geometry" },

  // Vectors & Matrices
  { word: "vector", hint: "A quantity having both magnitude and direction.", level: "hard", topic: "Vectors & Matrices" },
  { word: "magnitude", hint: "The length or size of a vector.", level: "hard", topic: "Vectors & Matrices" },
  { word: "direction", hint: "The orientation of a vector in space.", level: "hard", topic: "Vectors & Matrices" },
  { word: "scalar", hint: "A quantity having only magnitude, no direction.", level: "hard", topic: "Vectors & Matrices" },
  { word: "dot product", hint: "A way to multiply vectors resulting in a scalar.", level: "hard", topic: "Vectors & Matrices" },
  { word: "cross product", hint: "A way to multiply vectors resulting in another vector.", level: "hard", topic: "Vectors & Matrices" },
  { word: "matrix", hint: "A rectangular array of numbers arranged in rows and columns.", level: "hard", topic: "Vectors & Matrices" },
  { word: "determinant", hint: "A scalar value that can be computed from a square matrix.", level: "hard", topic: "Vectors & Matrices" },
  { word: "inverse matrix", hint: "A matrix that when multiplied by the original gives identity matrix.", level: "hard", topic: "Vectors & Matrices" },
  { word: "identity matrix", hint: "A square matrix with 1s on diagonal and 0s elsewhere.", level: "hard", topic: "Vectors & Matrices" },
  { word: "transpose", hint: "Flipping a matrix over its diagonal.", level: "hard", topic: "Vectors & Matrices" },
  { word: "gaussian elimination", hint: "A method for solving systems of linear equations.", level: "hard", topic: "Vectors & Matrices" },

  // Calculus - Limits & Continuity
  { word: "calculus", hint: "The mathematical study of continuous change.", level: "hard", topic: "Calculus - Limits & Continuity" },
  { word: "limit", hint: "The value that a function approaches as the input approaches some value.", level: "hard", topic: "Calculus - Limits & Continuity" },
  { word: "continuity", hint: "A function is continuous if it has no breaks or jumps.", level: "hard", topic: "Calculus - Limits & Continuity" },
  { word: "discontinuity", hint: "A point where a function is not continuous.", level: "hard", topic: "Calculus - Limits & Continuity" },
  { word: "asymptote", hint: "A line that a curve approaches but never touches.", level: "hard", topic: "Calculus - Limits & Continuity" },
  { word: "vertical asymptote", hint: "A vertical line that a function approaches.", level: "hard", topic: "Calculus - Limits & Continuity" },
  { word: "horizontal asymptote", hint: "A horizontal line that a function approaches.", level: "hard", topic: "Calculus - Limits & Continuity" },
  { word: "squeeze theorem", hint: "A method for finding limits by bounding functions.", level: "hard", topic: "Calculus - Limits & Continuity" },

  // Calculus - Derivatives
  { word: "derivative", hint: "Measures the instantaneous rate of change of a function.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "differentiation", hint: "The process of finding the derivative of a function.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "power rule", hint: "A rule for finding derivatives of power functions.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "product rule", hint: "A rule for finding derivatives of products of functions.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "quotient rule", hint: "A rule for finding derivatives of quotients of functions.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "chain rule", hint: "A rule for finding derivatives of composite functions.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "critical point", hint: "A point where the derivative is zero or undefined.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "local maximum", hint: "The highest point in a small region of a function.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "local minimum", hint: "The lowest point in a small region of a function.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "inflection point", hint: "A point where concavity changes.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "concavity", hint: "The direction a curve bends.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "optimization", hint: "Finding maximum or minimum values of functions.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "related rates", hint: "Finding rates of change of related quantities.", level: "hard", topic: "Calculus - Derivatives" },

  // Calculus - Integrals
  { word: "integral", hint: "Represents accumulation or area under a curve.", level: "hard", topic: "Calculus - Integrals" },
  { word: "integration", hint: "The process of finding the integral of a function.", level: "hard", topic: "Calculus - Integrals" },
  { word: "antiderivative", hint: "A function whose derivative is the given function.", level: "hard", topic: "Calculus - Integrals" },
  { word: "definite integral", hint: "An integral with specified limits of integration.", level: "hard", topic: "Calculus - Integrals" },
  { word: "indefinite integral", hint: "An integral without specified limits.", level: "hard", topic: "Calculus - Integrals" },
  { word: "fundamental theorem of calculus", hint: "Links differentiation and integration.", level: "hard", topic: "Calculus - Integrals" },
  { word: "u-substitution", hint: "A method for evaluating integrals by substitution.", level: "hard", topic: "Calculus - Integrals" },
  { word: "integration by parts", hint: "A method for evaluating integrals of products.", level: "hard", topic: "Calculus - Integrals" },
  { word: "area between curves", hint: "The area enclosed by two or more curves.", level: "hard", topic: "Calculus - Integrals" },
  { word: "volume of revolution", hint: "Volume created by rotating a curve around an axis.", level: "hard", topic: "Calculus - Integrals" },

  // Probability & Statistics
  { word: "normal distribution", hint: "Bell-shaped curve describing many natural phenomena.", level: "hard", topic: "Probability & Statistics" },
  { word: "standard deviation", hint: "A measure of how spread out numbers are.", level: "hard", topic: "Probability & Statistics" },
  { word: "variance", hint: "The square of the standard deviation.", level: "hard", topic: "Probability & Statistics" },
  { word: "z-score", hint: "The number of standard deviations from the mean.", level: "hard", topic: "Probability & Statistics" },
  { word: "confidence interval", hint: "A range of values likely to contain a population parameter.", level: "hard", topic: "Probability & Statistics" },
  { word: "hypothesis testing", hint: "A method for testing claims about populations.", level: "hard", topic: "Probability & Statistics" },
  { word: "regression", hint: "Finding relationships between variables.", level: "hard", topic: "Probability & Statistics" },
  { word: "correlation coefficient", hint: "A measure of the strength of linear relationship.", level: "hard", topic: "Probability & Statistics" },

  // Sequences & Series
  { word: "arithmetic sequence", hint: "A sequence with constant difference between terms.", level: "hard", topic: "Sequences & Series" },
  { word: "geometric sequence", hint: "A sequence with constant ratio between terms.", level: "hard", topic: "Sequences & Series" },
  { word: "arithmetic series", hint: "The sum of an arithmetic sequence.", level: "hard", topic: "Sequences & Series" },
  { word: "geometric series", hint: "The sum of a geometric sequence.", level: "hard", topic: "Sequences & Series" },
  { word: "convergence", hint: "Approaching a finite limit.", level: "hard", topic: "Sequences & Series" },
  { word: "divergence", hint: "Not approaching a finite limit.", level: "hard", topic: "Sequences & Series" },
  { word: "taylor series", hint: "Representing functions as infinite polynomials.", level: "hard", topic: "Sequences & Series" },
  { word: "maclaurin series", hint: "Taylor series centered at zero.", level: "hard", topic: "Sequences & Series" },

  // Differential Equations
  { word: "differential equation", hint: "An equation involving derivatives of a function.", level: "hard", topic: "Differential Equations" },
  { word: "ordinary differential equation", hint: "A DE with one independent variable.", level: "hard", topic: "Differential Equations" },
  { word: "partial differential equation", hint: "A DE with multiple independent variables.", level: "hard", topic: "Differential Equations" },
  { word: "separation of variables", hint: "A method for solving certain differential equations.", level: "hard", topic: "Differential Equations" },
  { word: "initial value problem", hint: "A differential equation with given initial conditions.", level: "hard", topic: "Differential Equations" },

  // Advanced Topics
  { word: "complex analysis", hint: "Study of functions of complex variables.", level: "hard", topic: "Advanced Topics" },
  { word: "number theory", hint: "Study of properties and relationships of numbers.", level: "hard", topic: "Advanced Topics" },
  { word: "abstract algebra", hint: "Study of algebraic structures like groups and rings.", level: "hard", topic: "Advanced Topics" },
  { word: "linear algebra", hint: "Study of vectors, vector spaces, and linear transformations.", level: "hard", topic: "Advanced Topics" },
  { word: "topology", hint: "Study of properties preserved through continuous deformations.", level: "hard", topic: "Advanced Topics" },
  { word: "combinatorics", hint: "Study of counting, arrangement, and combination.", level: "hard", topic: "Advanced Topics" },
  { word: "graph theory", hint: "Study of graphs and networks.", level: "hard", topic: "Advanced Topics" },
  // Mathematical Reasoning & Proof
  { word: "proof", hint: "A logical argument that establishes the truth of a statement.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "theorem", hint: "A mathematical statement that has been proven true.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "lemma", hint: "A helper theorem used in proving a larger theorem.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "corollary", hint: "A theorem that follows easily from another theorem.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "axiom", hint: "A statement accepted as true without proof.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "postulate", hint: "Another term for axiom; a basic assumption.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "conjecture", hint: "An unproven mathematical statement.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "counterexample", hint: "An example that disproves a statement.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "deductive reasoning", hint: "Reasoning from general principles to specific cases.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "inductive reasoning", hint: "Reasoning from specific cases to general principles.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "contradiction", hint: "A proof method assuming the opposite of what you want to prove.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "contrapositive", hint: "A logical equivalent of a conditional statement.", level: "hard", topic: "Mathematical Reasoning & Proof" },

  // Coordinate Geometry
  { word: "coordinate plane", hint: "A plane with two perpendicular number lines for locating points.", level: "medium", topic: "Coordinate Geometry" },
  { word: "x-axis", hint: "The horizontal number line on a coordinate plane.", level: "medium", topic: "Coordinate Geometry" },
  { word: "y-axis", hint: "The vertical number line on a coordinate plane.", level: "medium", topic: "Coordinate Geometry" },
  { word: "abscissa", hint: "The x-coordinate of a point.", level: "medium", topic: "Coordinate Geometry" },
  { word: "ordinate", hint: "The y-coordinate of a point.", level: "medium", topic: "Coordinate Geometry" },
  { word: "slope-intercept form", hint: "y = mx + b, a way to write linear equations.", level: "medium", topic: "Coordinate Geometry" },
  { word: "point-slope form", hint: "y - y₁ = m(x - x₁), another way to write linear equations.", level: "medium", topic: "Coordinate Geometry" },
  { word: "standard form", hint: "Ax + By = C, a way to write linear equations.", level: "medium", topic: "Coordinate Geometry" },
  { word: "distance formula", hint: "Formula for finding distance between two points.", level: "medium", topic: "Coordinate Geometry" },
  { word: "midpoint formula", hint: "Formula for finding the midpoint between two points.", level: "medium", topic: "Coordinate Geometry" },

  // Mathematical Notation & Symbols
  { word: "notation", hint: "A system of symbols used to represent mathematical ideas.", level: "medium", topic: "Mathematical Notation & Symbols" },
  { word: "symbol", hint: "A mark or character used to represent something.", level: "medium", topic: "Mathematical Notation & Symbols" },
  { word: "sigma notation", hint: "A way to write sums using the Greek letter sigma.", level: "hard", topic: "Mathematical Notation & Symbols" },
  { word: "summation", hint: "The process of adding a sequence of numbers.", level: "hard", topic: "Mathematical Notation & Symbols" },
  { word: "product notation", hint: "A way to write products using the Greek letter pi.", level: "hard", topic: "Mathematical Notation & Symbols" },
  { word: "factorial", hint: "The product of all positive integers up to a given number.", level: "hard", topic: "Mathematical Notation & Symbols" },
  { word: "absolute value notation", hint: "Using vertical bars to denote absolute value.", level: "medium", topic: "Mathematical Notation & Symbols" },
  { word: "set notation", hint: "Symbols and rules for describing sets.", level: "medium", topic: "Mathematical Notation & Symbols" },

  // Mathematical Sets
  { word: "set", hint: "A collection of distinct objects.", level: "medium", topic: "Mathematical Sets" },
  { word: "element", hint: "An object that belongs to a set.", level: "medium", topic: "Mathematical Sets" },
  { word: "subset", hint: "A set whose elements are all contained in another set.", level: "medium", topic: "Mathematical Sets" },
  { word: "union", hint: "The set containing all elements from given sets.", level: "medium", topic: "Mathematical Sets" },
  { word: "intersection", hint: "The set containing elements common to given sets.", level: "medium", topic: "Mathematical Sets" },
  { word: "complement", hint: "Elements not in a given set but in a universal set.", level: "medium", topic: "Mathematical Sets" },
  { word: "empty set", hint: "A set with no elements.", level: "medium", topic: "Mathematical Sets" },
  { word: "universal set", hint: "The set containing all possible elements.", level: "medium", topic: "Mathematical Sets" },
  { word: "Venn diagram", hint: "A diagram using circles to show relationships between sets.", level: "medium", topic: "Mathematical Sets" },

  // Mathematical Logic
  { word: "logic", hint: "The study of reasoning and argument.", level: "hard", topic: "Mathematical Logic" },
  { word: "statement", hint: "A declarative sentence that is either true or false.", level: "hard", topic: "Mathematical Logic" },
  { word: "conditional", hint: "An 'if-then' statement.", level: "hard", topic: "Mathematical Logic" },
  { word: "converse", hint: "Reversing the hypothesis and conclusion of a conditional.", level: "hard", topic: "Mathematical Logic" },
  { word: "inverse", hint: "Negating both parts of a conditional.", level: "hard", topic: "Mathematical Logic" },
  { word: "biconditional", hint: "An 'if and only if' statement.", level: "hard", topic: "Mathematical Logic" },
  { word: "quantifier", hint: "Words like 'for all' or 'there exists' in logic.", level: "hard", topic: "Mathematical Logic" },
  { word: "truth value", hint: "Whether a statement is true or false.", level: "hard", topic: "Mathematical Logic" },
  { word: "truth table", hint: "A table showing all possible truth values of a logical statement.", level: "hard", topic: "Mathematical Logic" },

  // Mathematical Modeling
  { word: "model", hint: "A mathematical representation of a real-world situation.", level: "hard", topic: "Mathematical Modeling" },
  { word: "parameter", hint: "A constant in a mathematical model that can be varied.", level: "hard", topic: "Mathematical Modeling" },
  { word: "variable", hint: "A quantity that can change in a mathematical model.", level: "hard", topic: "Mathematical Modeling" },
  { word: "constraint", hint: "A limitation or restriction in a mathematical model.", level: "hard", topic: "Mathematical Modeling" },
  { word: "simulation", hint: "Using a model to imitate a real process.", level: "hard", topic: "Mathematical Modeling" },
  { word: "algorithm", hint: "A step-by-step procedure for solving a problem.", level: "hard", topic: "Mathematical Modeling" },

  // Advanced Functions
  { word: "periodic function", hint: "A function that repeats its values at regular intervals.", level: "hard", topic: "Advanced Functions" },
  { word: "piecewise function", hint: "A function defined by different formulas on different intervals.", level: "hard", topic: "Advanced Functions" },
  { word: "composite function", hint: "A function formed by applying one function to the result of another.", level: "hard", topic: "Advanced Functions" },
  { word: "inverse function", hint: "A function that reverses the action of another function.", level: "hard", topic: "Advanced Functions" },
  { word: "one-to-one function", hint: "A function where each output corresponds to exactly one input.", level: "hard", topic: "Advanced Functions" },
  { word: "onto function", hint: "A function where every element in the range is used.", level: "hard", topic: "Advanced Functions" },
  { word: "even function", hint: "A function symmetric about the y-axis.", level: "hard", topic: "Advanced Functions" },
  { word: "odd function", hint: "A function symmetric about the origin.", level: "hard", topic: "Advanced Functions" },

  // Advanced Geometry Concepts
  { word: "congruence", hint: "Having the same shape and size.", level: "medium", topic: "Advanced Geometry Concepts" },
  { word: "similarity", hint: "Having the same shape but not necessarily the same size.", level: "medium", topic: "Advanced Geometry Concepts" },
  { word: "isometry", hint: "A transformation that preserves distance and shape.", level: "hard", topic: "Advanced Geometry Concepts" },
  { word: "homothety", hint: "A transformation that enlarges or reduces a figure.", level: "hard", topic: "Advanced Geometry Concepts" },
  { word: "projection", hint: "Mapping points from one space to another.", level: "hard", topic: "Advanced Geometry Concepts" },

  // Number Systems
  { word: "binary", hint: "Base-2 number system using only 0 and 1.", level: "medium", topic: "Number Systems" },
  { word: "hexadecimal", hint: "Base-16 number system using 0-9 and A-F.", level: "medium", topic: "Number Systems" },
  { word: "octal", hint: "Base-8 number system using digits 0-7.", level: "medium", topic: "Number Systems" },
  { word: "base", hint: "The number of digits used in a number system.", level: "medium", topic: "Number Systems" },
  { word: "place value system", hint: "A system where a digit's value depends on its position.", level: "medium", topic: "Number Systems" },

  // Mathematical Applications
  { word: "application", hint: "Using mathematics to solve real-world problems.", level: "medium", topic: "Mathematical Applications" },
  { word: "modeling", hint: "Creating mathematical representations of real situations.", level: "medium", topic: "Mathematical Applications" },
  { word: "prediction", hint: "Using mathematics to forecast future outcomes.", level: "medium", topic: "Mathematical Applications" },
  { word: "analysis", hint: "Examining mathematical relationships and patterns.", level: "medium", topic: "Mathematical Applications" },

  // Additional Advanced Topics
  { word: "manifold", hint: "A topological space that locally resembles Euclidean space.", level: "hard", topic: "Advanced Topics" },
  { word: "tensor", hint: "A mathematical object that generalizes scalars, vectors, and matrices.", level: "hard", topic: "Advanced Topics" },
  { word: "eigenvalue", hint: "A special number associated with a linear transformation.", level: "hard", topic: "Advanced Topics" },
  { word: "eigenvector", hint: "A vector that only changes by a scalar factor when a linear transformation is applied.", level: "hard", topic: "Advanced Topics" },
  { word: "metric space", hint: "A set with a defined distance function.", level: "hard", topic: "Advanced Topics" },
  { word: "homeomorphism", hint: "A continuous function with a continuous inverse.", level: "hard", topic: "Advanced Topics" },
  { word: "isomorphism", hint: "A structure-preserving mapping between two structures.", level: "hard", topic: "Advanced Topics" },
  { word: "homomorphism", hint: "A structure-preserving map between two algebraic structures.", level: "hard", topic: "Advanced Topics" },

  // Additional Counting & Measurement Terms
  { word: "ream", hint: "500 sheets of paper.", level: "medium", topic: "Counting Numbers" },
  { word: "bolt", hint: "40 yards of cloth.", level: "medium", topic: "Counting Numbers" },
  { word: "stone", hint: "14 pounds (British unit of weight).", level: "medium", topic: "Measurement" },
  { word: "furlong", hint: "220 yards or 1/8 mile.", level: "medium", topic: "Measurement" },
  { word: "chain", hint: "22 yards or 100 links.", level: "medium", topic: "Measurement" },
  { word: "rod", hint: "5.5 yards or 16.5 feet.", level: "medium", topic: "Measurement" },

  // Additional Geometry Terms
  { word: "dodecahedron", hint: "A polyhedron with twelve faces.", level: "medium", topic: "Basic Geometry" },
  { word: "icosahedron", hint: "A polyhedron with twenty faces.", level: "medium", topic: "Basic Geometry" },
  { word: "torus", hint: "A doughnut-shaped surface.", level: "hard", topic: "Advanced Geometry" },
  { word: "mobius strip", hint: "A surface with only one side and one boundary.", level: "hard", topic: "Advanced Geometry" },
  { word: "klein bottle", hint: "A surface with no interior or exterior.", level: "hard", topic: "Advanced Geometry" },

  // Additional Algebra Terms
  { word: "resultant", hint: "A polynomial in the coefficients of two polynomials.", level: "hard", topic: "Advanced Algebra" },
  { word: "discriminant", hint: "An expression that gives information about polynomial roots.", level: "hard", topic: "Advanced Algebra" },
  { word: "sylvester matrix", hint: "A matrix used to compute the resultant of two polynomials.", level: "hard", topic: "Advanced Algebra" },

  // Additional Calculus Terms
  { word: "jacobian", hint: "The determinant of the matrix of all first-order partial derivatives.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "hessian", hint: "A square matrix of second-order partial derivatives.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "gradient", hint: "A vector of partial derivatives of a scalar field.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "divergence", hint: "A scalar operator that measures vector field source at a point.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "curl", hint: "A vector operator that describes infinitesimal rotation of a 3D vector field.", level: "hard", topic: "Calculus - Derivatives" },
  { word: "laplacian", hint: "A differential operator given by the divergence of the gradient.", level: "hard", topic: "Calculus - Derivatives" },

  // Additional Statistics Terms
  { word: "quartile", hint: "Values that divide a data set into four equal parts.", level: "medium", topic: "Statistics & Probability" },
  { word: "percentile", hint: "Value below which a given percentage of observations fall.", level: "medium", topic: "Statistics & Probability" },
  { word: "skewness", hint: "Measure of asymmetry in a probability distribution.", level: "hard", topic: "Probability & Statistics" },
  { word: "kurtosis", hint: "Measure of tailedness of a probability distribution.", level: "hard", topic: "Probability & Statistics" },
  { word: "covariance", hint: "Measure of joint variability of two random variables.", level: "hard", topic: "Probability & Statistics" },

  // Additional Number Theory Terms
  { word: "modular arithmetic", hint: "Arithmetic system for integers where numbers wrap around.", level: "hard", topic: "Number Theory & Properties" },
  { word: "congruence", hint: "Equivalence relation in modular arithmetic.", level: "hard", topic: "Number Theory & Properties" },
  { word: "fermat's theorem", hint: "If p is prime, then a^(p-1) ≡ 1 mod p for any integer a.", level: "hard", topic: "Number Theory & Properties" },
  { word: "euler's theorem", hint: "Generalization of Fermat's theorem to composite moduli.", level: "hard", topic: "Number Theory & Properties" },
  { word: "goldbach conjecture", hint: "Every even integer greater than 2 can be expressed as sum of two primes.", level: "hard", topic: "Number Theory & Properties" },
  { word: "twin primes", hint: "Prime numbers that differ by 2.", level: "hard", topic: "Number Theory & Properties" },

  // Additional Mathematical Concepts
  { word: "golden ratio", hint: "Approximately 1.618, appears in mathematics and art.", level: "medium", topic: "Mathematical Properties & Relationships" },
  { word: "fibonacci sequence", hint: "Sequence where each number is sum of two preceding ones.", level: "medium", topic: "Sequences & Series" },
  { word: "pascal's triangle", hint: "Triangular array of binomial coefficients.", level: "medium", topic: "Algebra Basics" },
  { word: "binomial theorem", hint: "Describes algebraic expansion of powers of a binomial.", level: "hard", topic: "Advanced Algebra" },
  { word: "multinomial theorem", hint: "Generalization of binomial theorem to polynomials.", level: "hard", topic: "Advanced Algebra" },

  // Mathematical Constants
  { word: "e", hint: "Base of natural logarithm, approximately 2.71828.", level: "hard", topic: "Mathematical Notation & Symbols" },
  { word: "phi", hint: "Golden ratio, approximately 1.61803.", level: "hard", topic: "Mathematical Notation & Symbols" },
  { word: "i", hint: "Imaginary unit, square root of -1.", level: "hard", topic: "Mathematical Notation & Symbols" },
  { word: "infinity", hint: "Concept of something without any bound.", level: "medium", topic: "Mathematical Notation & Symbols" },

  // Mathematical Operations & Processes
  { word: "iteration", hint: "Repeating a process using previous output as new input.", level: "medium", topic: "Problem Solving" },
  { word: "recursion", hint: "Defining something in terms of itself.", level: "hard", topic: "Problem Solving" },
  { word: "induction", hint: "Method of mathematical proof.", level: "hard", topic: "Mathematical Reasoning & Proof" },
  { word: "extrapolation", hint: "Estimating values outside known data range.", level: "hard", topic: "Statistics & Probability" },
  { word: "interpolation", hint: "Estimating values within known data range.", level: "hard", topic: "Statistics & Probability" }
];